[project]
name = "okapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tkinter",
]

[dependency-groups]
dev = [
    "nuitka>=2.8.9",
]

